firefly: #namespace

    n_actions: 2 # We have 2 actions: relative position of reference goal w.r.t load position

    work_space: # 3D cube in which Drone is allowed to move
      x_max: 4.0
      x_min: 0.0
      y_max: 2
      y_min: -2
      z_max: 2.0
      z_min: 0.0

    max_roll: 1.57 # Max roll after which we end the episode
    max_pitch: 1.57 # Max roll after which we end the episode
    max_yaw: 3.14 # Max yaw, its 4 because its bigger the pi, its a complete turn actually the maximum
    visualization: True
